fix int overflow exception in unittest
Fixes:

File ".../versioning/version.py", line 30, in __init__
    if self < 0:
OverflowError: Python int too large to convert to C long